[package]
name = "hexaminas"
version = "0.1.0"
authors = ["Adrián Arroyo Calle <adrian.arroyocalle@gmail.com>"]

[dependencies]
piston_window = "*"
piston2d-graphics = "0.26.0"
rand = "*"
piston = "*"
